version: '2'

services:

  crdb:
    image: cockroachdb/cockroach:v19.1.1
    command: start --insecure
    ports:
      - "8080:8080"
      - "26257:26257"

  dbmate:
    image: amacneil/dbmate
    command: up
    environment:
      - "DATABASE_URL=postgres://root@192.168.45.21:26257/crawl_db?sslmode=disable"
    volumes:
      - ./db:/db
    restart: on-failure

